// Code generated by mockery v2.33.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IStringSet is an autogenerated mock type for the IStringSet type
type IStringSet struct {
	mock.Mock
}

// Add provides a mock function with given fields: v
func (_m *IStringSet) Add(v string) {
	_m.Called(v)
}

// RandomN provides a mock function with given fields: n
func (_m *IStringSet) RandomN(n int) []string {
	ret := _m.Called(n)

	var r0 []string
	if rf, ok := ret.Get(0).(func(int) []string); ok {
		r0 = rf(n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// Remove provides a mock function with given fields: v
func (_m *IStringSet) Remove(v string) {
	_m.Called(v)
}

// NewIStringSet creates a new instance of IStringSet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIStringSet(t interface {
	mock.TestingT
	Cleanup(func())
}) *IStringSet {
	mock := &IStringSet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
